Basic script for populating db
cornell-dti/idol pull request #101
Opened 2021-04-19 03:53 UTC by riyajaggi

### Summary 

This pull request is the first step towards populating the teams db in idol. This makes use of existing member documents and adds them to the team collections based on their role and subteam.

### Test Plan 

Ensure all team endpoints are working correctly after populating the db

### Notes 

This still needs some work.

### Breaking Changes 

- no change in schema
- need to ensure all teams are updated correctly

2021-04-21 14:16 UTC, SamChou19815 requested changes

2021-04-21 14:16 UTC, SamChou19815 commented on backend/data/firebase.ts
> +const serviceAccount = require('backend/resources/cornelldti-idol-firebase-adminsdk-ifi28-9aaca97159.json');
could you fix these linter errors and warnings first

2021-04-21 14:16 UTC, SamChou19815 commented on backend/data/populate-teams.ts
> +    console.log(teamData);
this function doesn't seem to do anything at the moment, due to this db code being commented out

2021-04-21 19:24 UTC, henry-li-06 commented
I'm not sure if we really need to keep the script to populate `teams` collection. We theoretically won't ever need to mass populate the collection again since teams can be added/deleted/edited from the _Edit Teams_ page. Thoughts @SamChou19815?

2021-04-21 19:32 UTC, SamChou19815 commented
@henry-li-06 good point. Also why are we keeping the teams collection if the team information can already be inferred from the subteam field?

2021-04-21 21:51 UTC, henry-li-06 commented
@SamChou19815 I guess we don't necessarily need the teams collection since the entirety of the collection can be derived from the members collection and the relationship between members and teams adds some complexity to our data. But at the same time I think operations on teams would be less computationally wasteful if we leave the collection (ex. don't need to go through all members to delete a team).

2021-04-22 14:30 UTC, SamChou19815 commented
@henry-li-06 Given that we are only deal with data set with size around 100, I think that kind of performance benefits are negligible, but the cost of syncing the data in two collections are real. That being said, I'm ok with #103 merged if breaks are fixed, since we need to fix the subteam issue first.

2021-05-03 21:16 UTC, closed without merging