Sign in link
cornell-dti/idol pull request #118
Opened 2021-05-08 02:25 UTC by JBoss925

### Summary 
Added a sign in link functionality

This replaces bit.ly, and allows us to automatically track sign in forms.

We can provide a deeplink like:
`https://idol.cornelldti.org/forms/signin/<id>`
to automatically sign the user in when they log in with google (or automatically if already logged in).

It also rearranges the menu system quite substantially. But it definitely makes more sense to me, and it allows us to demo the forms section and let people play with it at all hands.

### Test Plan
Tested locally on dev db instance, and it works! It's really just basic document CRUD stuff lol.

- Added a new Firebase collection called sign-in-forms to hold, you guessed it, sign-in forms

2021-05-08 02:52 UTC, henry-li-06 commented on frontend/src/environment.ts
> +export const useProdDb = false;
this should be changed back to `true`

2021-05-08 03:30 UTC, JBoss925 commented on frontend/src/environment.ts
> +export const useProdDb = false;
good catch lol

2021-05-09 02:23 UTC, SamChou19815 requested changes
Put a break on this. Let's do the routes refactoring first before introducing the signin links features.

2021-05-09 22:46 UTC, SamChou19815 approved these changes

2021-05-09 22:46 UTC, merged