Display count for shoutouts
cornell-dti/idol pull request #462
Opened 2023-05-02 05:45 UTC by oscarwang20

### Summary 

This pull request adds a count display for admin shoutouts, inlcuding:
- a display for the number of shoutouts in the date range and the total number of shoutouts (for "ALL" and "HIDDEN")
- a more flashy count display for the present view and numbers for each shoutout 

### Notion/Figma Link 
https://www.notion.so/cornelldti/Shoutouts-Display-count-and-total-number-of-shoutouts-666ddaa1034343d08d5a3d94c3617d7a?pvs=4

### Test Plan 

default date range
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/69322572/235587103-86a4d045-b0fe-4734-a5eb-2d58ca0d504f.png">
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/69322572/235587132-37c0a25a-90de-4cb7-be95-43a77ea1e378.png">
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/69322572/235587078-f6879a84-10ea-41e3-b9da-1542a8243dc7.png">

all shoutouts
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/69322572/235587215-652a8d5a-acb7-4030-becb-d00cff6df1c0.png">
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/69322572/235587226-d0d3a537-752d-4262-818a-c057d1b192a3.png">
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/69322572/235587243-5924405c-07d6-4460-81c6-eaab53f794a9.png">

### Notes 

- I just kept the original styling for the headers with the counts, but I'd love to hear any suggestions on how to improve it
- While finishing this ticket I had an idea for another shoutouts feature where we put some content at the bottom of the present page -- here's what I have so far: https://www.notion.so/cornelldti/shoutouts-end-content-256a37a6c6444fe5b452a327dc372fbd?pvs=4

2023-05-02 06:27 UTC, andrew032011 requested changes

2023-05-02 06:27 UTC, andrew032011 commented on frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
> +            <img
It is recommended that you use the `Image` component provided by SemanticUI: https://react.semantic-ui.com/elements/image/.

2023-05-02 06:27 UTC, andrew032011 commented on frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
> +          <header className={styles.presentCount}>
I'd use the `Header` component from semanticUI

2023-05-02 06:27 UTC, andrew032011 commented on frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
> +        <Header className={styles.formTitle} content={title}></Header>
There's no content in this `Header` component, so we can rewrite as `<Header className={styles.formTitle} content={title}/>`. Or `<Header className={styles.formTitle}>{title}</Header>`. But I wouldn't leave it as an empty component.

2023-05-02 06:27 UTC, andrew032011 commented on frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
> +    if (view === 'PRESENT') {
I would keep these two if-statements consistent, especially since they're both one-liners. Maybe no curly brackets?

2023-05-02 06:27 UTC, andrew032011 commented on frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
> +              src="https://emojis.slackmojis.com/emojis/images/1660853767/60881/meow_attention.gif?1660853767"
I don't love that these emojis are not stored on our servers. If this link were to ever break, then we'd lose the image. Can you store it in `frontend/src/static/images` please?

2023-05-02 06:27 UTC, andrew032011 commented on frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
> +    let title = `Showing ${displayShoutouts.length} of ${allShoutouts.length} shoutouts`;
Maybe this was a design decision you agreed on in work session, but I don't know if putting the total number of shoutouts makes sense. This number will only grow and grow as time goes on (unless we clear these out of the DB each semester?). It just doesn't seem like a number that's very relevant.

2023-05-02 16:27 UTC, andrew032011 commented on frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
> +    let title = `Showing ${displayShoutouts.length} of ${allShoutouts.length} shoutouts`;
@oscarwang20 Thanks for adding this change. I think I should have made this design choice more open for discussion. Could you make a post in #idol-devs about this and see what other think?

2023-05-02 16:46 UTC, andrew032011 commented on frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
> +    let title = `All shoutouts (${displayShoutouts.length})`;
Capitalize "shoutouts" 

i.e. "All shoutouts"--> "All Shoutouts"

2023-05-02 16:46 UTC, andrew032011 commented on frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
> +            <Image className={styles.presentCountImg} src={catEmoji.src} alt="loading" />
Not sure if I agree with the "loading" alt string. Maybe pick something that's closer to what this really is?

2023-05-02 16:47 UTC, andrew032011 commented
Thanks for making those changes. Just a few more minor comments. And let's ask in #idol-dev about that "All Shoutouts" vs. displaying "Showing ___ of ____ shoutouts" text, just to be safe!

2023-05-02 16:56 UTC, kembayeb commented
> Thanks for making those changes. Just a few more minor comments. And let's ask in #idol-dev about that "All Shoutouts" vs. displaying "Showing ___ of ____ shoutouts" text, just to be safe!

I like all shoutouts,since that number would never be too big during an all hands. After an all hands we don't really worry about the previous weeks shoutouts.

2023-05-02 18:06 UTC, oscarwang20 commented
I just noticed a bug where if you click the corresponding button for a view ("ALL"/"HIDDEN"/"PRESENT") while it is displayed, then all shoutouts get displayed even though the date range is still the same. This seems to be an issue on the production side as well, but we probably didn't notice it without the count feature. I can look into this, but should it be another ticket?

2023-05-03 07:06 UTC, andrew032011 commented
> I just noticed a bug where if you click the corresponding button for a view ("ALL"/"HIDDEN"/"PRESENT") while it is displayed, then all shoutouts get displayed even though the date range is still the same. This seems to be an issue on the production side as well, but we probably didn't notice it without the count feature. I can look into this, but should it be another ticket?
> 
> Update: I fixed it by changing these lines to filter from `displayShoutouts` instead of `allShoutouts` https://github.com/cornell-dti/idol/blob/e344f61173c5532f4c9990c1e09c40901c06f55e/frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx#LL220C11-L230C26

I personally think it's fine if you want to just apply the fix here, especially since it's quick and you found it already.

2023-05-04 05:28 UTC, andrew032011 commented on frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.module.css
> +.ui.image {
Is this used in the styling? If not, we should remove it.

2023-05-04 05:29 UTC, andrew032011 approved these changes
Looks good. One minor comment and this should be good to merge in!

2023-05-08 23:30 UTC, merged