Add contributors to FA23 list
cornell-dti/idol pull request #477
Opened 2023-09-05 16:54 UTC by alyssayzhang

### Summary

2023-09-05 16:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cornell-dti/idol?pullRequest=477) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cornell-dti/idol?pullRequest=477) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cornell-dti/idol?pullRequest=477) it.</sub>

2023-09-05 16:55 UTC, andrew032011 commented
Please undo changes in `package.json` and `yarn.lock`.

2023-09-05 16:56 UTC, andrew032011 requested changes
Could you add a quick summary in the PR description?

2023-09-11 20:55 UTC, closed without merging

2023-09-11 20:55 UTC, alyssayzhang commented
creating a new PR do get rid of line diff