Allow admin to edit dev portfolios
cornell-dti/idol pull request #526
Opened 2023-10-21 20:37 UTC by patriciaahuang

### Summary

Admins can now edit a dev portfolio without having to delete and replace an assignment with a new version (which was not feasible once submissions have been made). 

Frontend changes include adding an edit button for each portfolio that opens an edit modal, a success message if an edit is made, and error messages if conditions are violated. 

Backend changes include adding a new update endpoint, and documenting the Dev Portfolio API.

### Test Plan

I tested if a dev portfolio is successfully edited by looking at the firebase database, and checking that it updated correctly.

Each portfolio card now has an edit button, which opens a form to edit the portfolio.
![Screen Shot 2023-10-21 at 4 24 22 PM](https://github.com/cornell-dti/idol/assets/125151386/58de69d8-98a1-432d-b9c4-8d6c8b2713e7)

The form has pre-populated values depending on the original portfolio.
![Screen Shot 2023-10-21 at 4 24 49 PM](https://github.com/cornell-dti/idol/assets/125151386/99737e03-2a5b-46d2-a075-c5254954daa3)

If a portfolio is successfully edited, a success message will appear and the original page will automatically rerender in the background to show the updated portfolio.
![Screen Shot 2023-10-21 at 4 27 14 PM](https://github.com/cornell-dti/idol/assets/125151386/9a4f10cc-757f-445e-95d0-0ad37a06c088)

An error message will appear if certain conditions are violated.
![Screen Shot 2023-10-21 at 4 28 33 PM](https://github.com/cornell-dti/idol/assets/125151386/68db1fb0-bfc2-4637-9bc4-197fb2c42958)

2023-10-21 21:23 UTC, kevinmram approved these changes
The new edit functionality significantly improves the users' interaction with the platform, streamlining the process of updating developer portfolios, rather than deleting them, saving time and reduce the possibility of errors or data inconsistencies!

2023-10-23 01:33 UTC, oscarwang20 requested changes

2023-10-23 01:33 UTC, oscarwang20 commented on frontend/src/API/DevPortfolioAPI.ts
We don't need `DevPortfolioResponseObj` since the error handling is already done by the API wrapper. Since `updateDevPortfolio` uses `PUT`, it should return the updated resource, so it should be `res.data.portfolio` like the other endpoints that modify a devPortfolio instance.

2023-10-23 01:47 UTC, andrew032011 reviewed
This is really excellent work. You're picking things up fast and your prior backend experience shows!

See my/Oscar's comments about the UI. They are minor, just some style considerations.

2023-10-23 01:47 UTC, andrew032011 commented on backend/tests/DevPortfolioAPI.test.ts
> +  test('deleteDevPortfolio should throw permission error', async () => {
👍

2023-10-23 01:47 UTC, andrew032011 commented on frontend/src/components/Admin/DevPortfolio/EditDevPortfolio.tsx
> +        ></AdminDevPortfolioForm>
nit:
```
<AdminDevPortfolioForm>
</AdminDevPortfolioForm>
```
can be rewritten as
```
<AdminDevPortfolioForm/>
```

2023-10-23 01:47 UTC, andrew032011 commented on frontend/src/components/Admin/DevPortfolio/AdminDevPortfolio.tsx
> +    Emitters.devPortfolioUpdated.subscribe(cb);
I think you can just pass `fullReset` directly in here. No need for the extra callback function.

2023-10-23 01:47 UTC, andrew032011 commented on frontend/src/API/DevPortfolioAPI.ts
To add on, it's excellent that you're doing error handling here, but we generally don't want to expose these error messages directly to the user on the UI. For now, since the only error we could really get is Internal Server Error or Permissions Error we don't really need to pass this info to the UI. 

I left a comment in `updateDevPortfolio` for how I would handle the error.

2023-10-23 01:47 UTC, andrew032011 commented on frontend/src/components/Admin/DevPortfolio/EditDevPortfolio.tsx
> +      if (val.error) {
`val === undefined` is a sign that the DevPortfolio update did not go through and some error was thrown. As developers, we can inspect the network tab or look at the backend logs to see further what went wrong here. No need to expose the error message itself on the UI.

2023-10-23 21:50 UTC, andrew032011 approved these changes

2023-10-27 22:30 UTC, oscarwang20 approved these changes

2023-10-30 04:44 UTC, merged