Implement new website footer
cornell-dti/idol pull request #534
Opened 2023-10-30 22:16 UTC by alyssayzhang

### Summary 

This pull request is the first step towards implementing the Footer of the new website. 

- [x] implement footer on mobile, tablet, and desktop screens.

### Notion/Figma Link 
- https://www.notion.so/Idol-FA23-4899da48384747ba8ef8366f034e5ebf?p=2940bc4975d44c81bc3987de83b6820c&pm=s

Desktop 
<img width="1416" alt="Screenshot 2023-10-30 at 6 14 01 PM" src="https://github.com/cornell-dti/idol/assets/69472409/2d63f475-716a-41a2-82fe-a9d2710e026a">

Tablet 
<img width="791" alt="Screenshot 2023-10-30 at 6 14 54 PM" src="https://github.com/cornell-dti/idol/assets/69472409/60919ea3-6ef7-4c44-a6c8-cdb8c3191d98">

Mobile
<img width="537" alt="Screenshot 2023-10-30 at 6 15 11 PM" src="https://github.com/cornell-dti/idol/assets/69472409/3b732467-8148-4765-a1e1-793a962459dc">

### Notes 
- This is the preliminary footer for the website since the designers might make more changes to the footer. On tablets, the text takes up 2 lines of space.

2023-11-03 03:08 UTC, andrew032011 commented on new-dti-website/components/footer.tsx
> +import styles from './Header.module.css';
Remove this import

2023-11-03 03:09 UTC, andrew032011 reviewed
Run prettier? `yarn run format`

2023-11-03 04:41 UTC, andrew032011 requested changes

2023-11-03 04:41 UTC, andrew032011 commented on new-dti-website/src/app/layout.tsx
> +    </div>
Place `{children}` here

2023-11-03 04:41 UTC, andrew032011 commented on new-dti-website/src/app/page.tsx
>    <div>
`Navbar` and `Footer` actually should not be in the `Home` component, since they apply to all pages. We should actually remove both components here.

2023-11-05 03:48 UTC, alyssayzhang commented on new-dti-website/src/app/layout.tsx
> +export const ibm_plex_mono = IBM_Plex_Mono({
yes the font for the footer is` IBM_Plex_Mono`

2023-11-05 03:50 UTC, andrew032011 commented on new-dti-website/src/app/layout.tsx
> +export const ibm_plex_mono = IBM_Plex_Mono({
Great! Thanks for clarifying. This looks fine then :).

2023-11-05 04:40 UTC, andrew032011 approved these changes

2023-11-06 16:38 UTC, merged