added documentation, shoutoutAPI
cornell-dti/idol pull request #579
Opened 2024-02-12 03:50 UTC by kevinmram

added documentation to shoutoutAPI- documenting the purpose and usage of each method within the class.

2024-02-12 15:31 UTC, oscarwang20 requested changes

2024-02-12 16:11 UTC, andrew032011 requested changes
I find it a bit redundant to mention permissions in the docstring. I think in general it is implied. If we want to include info about permissions here, we should be more specific as to what we're checking. Otherwise, I might remove it (you can keep the @throws).

Also soon we'll have an auth model that takes care of some of this logic.

2024-03-04 06:33 UTC, andrew032011 approved these changes

2024-03-04 08:48 UTC, oscarwang20 approved these changes

2024-03-04 18:08 UTC, merged