Set up firebase for coffee chat bingo
cornell-dti/idol pull request #593
Opened 2024-03-24 04:18 UTC by alyssayzhang

### Summary 

This pull request is the first step towards implementing feature Foo

- [x] implemented X
- [ ] fixed Y

- [ ] Updated backend api specification

### Notion/Figma Link 

### Test Plan 

### Notes 

### Breaking Changes 

- Database schema change (anything that changes Firestore collection structure)
- Other change that could cause problems (Detailed in notes)

2024-03-24 05:10 UTC, patriciaahuang reviewed
The set up looks good in the prod database! You probably did some testing in the dev database, so there's an extra coffee-chat-requirement collection. In order to keep the dev database updated with the prod, you may want to remove it.

2024-03-27 22:26 UTC, oscarwang20 requested changes

2024-03-27 22:26 UTC, oscarwang20 commented on backend/src/types/DataTypes.d.ts
> +  status: string;
Make sure to add this new type to `common-types/index.d.ts` as well!

2024-03-31 00:55 UTC, andrew032011 approved these changes
A few nits, but overall looks good

2024-03-31 00:55 UTC, andrew032011 commented on backend/src/types/DataTypes.d.ts
> +  status: string;
Change `status` type to be `Status`, not `string`.

2024-03-31 00:55 UTC, andrew032011 commented on common-types/index.d.ts
> +  readonly uuid: string;
As you can see (from above), though we never followed this rule, we theoretically should be making all these fields `readonly`. Don't worry about the above ones but let's fix this one.

2024-04-15 22:25 UTC, oscarwang20 approved these changes
Looks good to me! Thanks again for finishing this :D

2024-04-15 23:22 UTC, merged