Add team page hero and about
cornell-dti/idol pull request #603
Opened 2024-04-15 03:49 UTC by cchrischen

### Summary 

This pull request adds the team page's hero and about component.  The components are responsive for tablet and mobile designs as described by the Figma file. One noteworthy difference is that the carousel will only display 3 items in laptop mode, while the Figma has it as 5.

### Notion/Figma Link 
https://www.figma.com/file/jKbvR1jVr1k80GGWnCpiRT/Website-Designs-SP23%2FFA23?type=design&node-id=5464-9095&mode=design&t=lWkLy75pZ38bsFDV-0

### Test Plan 

https://github.com/cornell-dti/idol/assets/144409850/1a88b8ff-ad88-4af6-b794-dcab457b9af7

### Notes 
**Note:** The image files needed for these sections are not included in this PR. This will be fixed when #591 is merged into main.

2024-05-06 02:24 UTC, oscarwang20 commented
I can't click and drag on the carousel from the middle image. Is this the intended functionality?

2024-05-06 02:42 UTC, oscarwang20 commented on new-dti-website/components/navbar.tsx
> +    <div className="relative z-20">
Thanks for adding this :)

2024-05-06 02:50 UTC, oscarwang20 requested changes
Thanks for adding everything, it looks really great! Can we try to make the carousel draggable from the middle–at least on the mobile layout b/c the scrolling is a little inaccessible right now.

2024-05-06 05:45 UTC, andrew032011 approved these changes
Looks good, I'd fix the carousel issue as well but otherwise it looks really great. Feel free to implement/ignore the nitpicks.

2024-05-06 05:45 UTC, andrew032011 commented on new-dti-website/components/team/TeamAbout.tsx
> +  const radius = 175;
It would be nice to extract these numbers out as constants outside of the component, maybe at the top of the file so they're easier to find?

2024-05-06 05:45 UTC, andrew032011 commented on new-dti-website/components/team/TeamHero.tsx
> +        setCarouselIndex(carouselApi.selectedScrollSnap());
👍 very cool

2024-05-06 05:45 UTC, andrew032011 commented on new-dti-website/components/team/TeamHero.tsx
> +                    {`${carouselImages.images[carouselIndex % 6].alt}.jpg`}
6 feels like a magic number to me. can we use another value to calculate 6? Or if it's temporary, can you make it a constant and move it up a level so it's easier to find/we see that it's a fixed constant?

2024-05-06 05:45 UTC, andrew032011 commented on new-dti-website/components/team/TeamAbout.tsx
> +              {chartSection
Would be nice to move this calculation into a helper function

2024-05-06 05:45 UTC, andrew032011 commented on new-dti-website/components/team/TeamAbout.tsx
> +        const percentage = roleStats[role].people / allMembers.length;
Would be nice to move this code into a helper function and then call it here

2024-05-06 05:45 UTC, andrew032011 commented on new-dti-website/components/team/TeamAbout.tsx
> +  allMembers.forEach((member: IdolMember) => {
generally discouraged to write this imperatively like this for each render. Could you potentially write it functionally? (with an `.map(...)` + array, then convert to set)?

2024-08-27 14:28 UTC, andrew032011 approved these changes

2024-08-27 19:09 UTC, oscarwang20 approved these changes

2024-08-27 19:12 UTC, merged