add "Review" button to TEC (Admin)
cornell-dti/idol pull request #654
Opened 2024-10-07 03:13 UTC by kevinmram

add "Review" button to TEC (Admin), and view user submission w/ Set to Approved/Rejected.

- However, the attached image doesn't display and is replaced with a default image...

https://github.com/user-attachments/assets/de4a618b-e591-455e-a268-b79645b0cb75

2024-10-07 04:55 UTC, andrew032011 commented
> - However, the attached image doesn't display and is replaced with a default image...

https://github.com/cornell-dti/idol/pull/655

2024-10-27 20:26 UTC, patriciaahuang requested changes
Good job on this! I think reviewing a rejected team event submission shouldn't show the textbox for rejection reason, since the reviewer wouldn't have a rejection reason when approving the submission (and it'll be set to null no matter what reason they put).

<img width="892" alt="Screenshot 2024-10-27 at 4 19 58 PM" src="https://github.com/user-attachments/assets/8ac81235-ba08-4533-b77b-7c093a0372fd">

2024-10-27 20:26 UTC, patriciaahuang commented on frontend/src/components/Admin/TeamEvent/TeamEventCreditReview.tsx
> +        {/* Show 'Set to Rejected' only if the current status is approved */}
Remove comment

2024-10-27 20:26 UTC, patriciaahuang commented on frontend/src/components/Admin/TeamEvent/TeamEventCreditReview.tsx
> +        {/* Show 'Set to Approved' only if the current status is rejected */}
Remove comment

2024-10-27 21:44 UTC, patriciaahuang approved these changes
Left a suggestion to make the logic more concise, but otherwise looks good!

2024-10-27 21:44 UTC, patriciaahuang commented on frontend/src/components/Admin/TeamEvent/TeamEventCreditReview.tsx
> +        )}
```suggestion
        {currentStatus !== 'rejected' && (
          <Button basic color="red" disabled={reason === ''} onClick={rejectCreditRequest}
          >
            {currentStatus === 'pending' ? 'Reject' : 'Set to Rejected'}
          </Button>
        )}
        {currentStatus !== 'approved' && (
          <Button basic color="green" onClick={approveCreditRequest}
          >
            {currentStatus === 'pending' ? 'Approve' : 'Set to Approved'}
          </Button>
        )}
```

2024-10-27 22:19 UTC, andrew032011 approved these changes

2024-10-27 23:05 UTC, merged