Website Redesign: New product images
cornell-dti/idol pull request #771
Opened 2024-12-05 03:12 UTC by JasonMun7

### Summary 

This PR adds the new product images for the Product Page, effectively omitting the Floating Images component. (Keeping it for the future if needed!)

- [x] Added new Product Images in a new static folder in the public/images/public directory!
- [x] Removed the Floating images component the use of cn class! 
- [x] Updated products json to simply take a single image and a new image dimension!

### Notion/Figma Link 

[Redo Image Layout](https://www.notion.so/Products-Page-Redo-image-layout-1510ad723ce1804e8caffdca4a915fdd?pvs=4)

### Test Plan 

https://github.com/user-attachments/assets/33609548-1c52-480b-9b91-941814cc50b9

2024-12-05 04:50 UTC, andrew032011 approved these changes
Thanks! A few questions: 
1. Any unused images that we can delete now?
2. The images look kind of large (in size). Do you think it's possible to keep them within the 300 KB policy we've been following, without decreasing quality? I noticed they took awhile to load in.

2024-12-05 15:15 UTC, andrew032011 commented
CornellGo hasn't launched yet: I think it's fine to keep it without the button now and then sub it in once they launch? 

either way, filed a ticket to track: https://www.notion.so/Add-CornellGo-App-Store-Google-Play-Store-Link-To-Product-Page-1530ad723ce1805ea331d7a6253421a5?pvs=4

2024-12-05 15:17 UTC, Bookie0 requested changes
nice thank you! let's also try to improve the alt text of these images while we're at it :)

2024-12-05 15:17 UTC, Bookie0 commented on new-dti-website/components/products/products.json
>        "alt": "courseplan",
can we make the alt text a bit descriptive?

For example this is what Apple does for similar product mockups:
<img width="1525" alt="Screenshot 2024-12-05 at 10 03 58 AM" src="https://github.com/user-attachments/assets/bb99248d-3476-467a-b974-2f50dc67f0d5">


 I'll provide some suggestions in the review

2024-12-05 15:17 UTC, Bookie0 commented on new-dti-website/components/products/products.json
>        "link": "https://cureviews.org/",
alt for CU reviews:

> A laptop next to a phone, displaying the search page and the search results page of the CU Reviews website

2024-12-05 15:17 UTC, Bookie0 commented on new-dti-website/components/products/products.json
>        "alt": "courseplan",
```suggestion
      "alt": "An desktop computer next to a laptop, displaying the planning page and the profile page of the Course Plan website",
```

2024-12-05 15:17 UTC, Bookie0 commented on new-dti-website/components/products/products.json
>        "alt": "queue me in",
```suggestion
      "alt": "2 phones side by side, displaying the list of available consulting hours screen and the join queue screen of the Queue Me In website",
```

2024-12-05 15:17 UTC, Bookie0 commented on new-dti-website/components/products/products.json
>        "alt": "design at cornell",
```suggestion
      "alt": "A browser displaying the hero section of the Design @ Cornell website",
```

2024-12-05 15:17 UTC, Bookie0 commented on new-dti-website/components/products/products.json
>        "alt": "zing",
```suggestion
      "alt": "A desktop computer next to a tablet, displaying the landing page and questionnaire page of the Zing website",
```

2024-12-05 15:17 UTC, Bookie0 commented on new-dti-website/components/products/products.json
>        "alt": "cuapts",
```suggestion
      "alt": "A laptop next to a phone, displaying home page and an address page of the CU Apts website",
```

2024-12-05 15:17 UTC, Bookie0 commented on new-dti-website/components/products/products.json
>    "upcoming": [
Alt for Carriage:

> A monitor displaying a blurry screen of the Carriage website with the words "Coming Soon" overlaid on top

2024-12-05 16:41 UTC, JasonMun7 commented
> Thanks! A few questions:
> 
> 1. Any unused images that we can delete now?
> 2. The images look kind of large (in size). Do you think it's possible to keep them within the 300 KB policy we've been following, without decreasing quality? I noticed they took awhile to load in.

Yes I can remove the floating images within the public folder! Also, you right! I'll try to see if I can decrease their size! Thanks for that reminder Andrew!

2024-12-06 17:18 UTC, Bookie0 approved these changes
yay thanks!

2024-12-06 17:22 UTC, merged