Website: Add Sample Projects
cornell-dti/idol pull request #783
Opened 2024-12-07 18:32 UTC by cchrischen

### Summary 
Add sample projects from this semester's trends class. Currently have 4/5 we asked to see how the components looks when populated with data. Images were compressed to be < 300kb.

### Notion/Figma Link 
[Notion](https://www.notion.so/Idol-FA24-1030ad723ce1804ca825d0ec8972c711?p=13b0ad723ce180f9a9fce10540ed5c63&pm=s)

### Test Plan 
see netlify deploy

2024-12-07 18:49 UTC, andrew032011 commented
Might need to workshop which screenshots we pick.

2024-12-07 18:49 UTC, andrew032011 approved these changes

2024-12-07 19:15 UTC, Bookie0 requested changes
can we remove the animation when the project accordion opens up?
like it slowly fades in, but i dont think we're having this animation show up anywhere else

2024-12-12 22:00 UTC, Bookie0 approved these changes
nice!

can we also [remove the red](https://www.notion.so/Idol-Lead-Sync-781de97ad403492b94b420349f829ea5?pvs=4#1550ad723ce1800fbbf4dbc5fe1fea35) on open state

<img width="1339" alt="Screenshot 2024-12-12 at 4 59 29 PM" src="https://github.com/user-attachments/assets/ef3cd2e4-635a-41a5-a9d8-dc81b614d472" />

2024-12-12 22:00 UTC, Bookie0 commented on new-dti-website/components/course/data/student_projects.json
> +      "description": "A platform that helps students recover their lost belongings through crowdsourced data",
```suggestion
      "description": "A platform that helps students recover their lost belongings through crowdsourced data.",
```

2024-12-12 22:00 UTC, Bookie0 commented on new-dti-website/components/course/data/student_projects.json
> +      "description": "Centralized platform to find, join & create new events for OFF-campus events",
```suggestion
      "description": "Centralized platform to find, join & create new events for OFF-campus events.",
```

2024-12-12 22:01 UTC, Bookie0 commented on new-dti-website/components/course/data/student_projects.json
> +      "description": "A platform that helps students recover their lost belongings through crowdsourced data",
(adding period for consistency with the descriptions of the other projects)

2024-12-14 21:24 UTC, merged